/**:
  ros__parameters:
    common:
      database_storage: "mcap"                              # sqlite3 or mcap
      maximum_record_time: 36000                            # seconds
      maximum_allowed_bag_storage_size: 500.0               # GB
      maximum_bag_file_size: 20.0                           # GB
      enable_only_auto_mode_recording: false                # if enabled, recording occurs only "AUTO" mode
      number_of_maximum_bags: 1000                          # limit of stored bag file count
      path: "/home/robione/Files/bags/"                     # Path to bag file for saving
      prefix: "logging_ros2bag_"                            # Prefix for folder name
      minimum_acceptable_disk_space: 20                     # GB
      disk_space_threshold_action: "shutdown"               # [remove, shutdown] remove files or shutdown node
    raw_input_topics:                                       # for rosbag-replay (logging) simulation
      record_raw_input: true
      raw_input_topics:
        - /perception/object_recognition/detection/rois0
        - /perception/object_recognition/detection/rois1
        - /perception/object_recognition/detection/rois2
        - /perception/object_recognition/detection/rois3
        - /sensing/camera/camera0/camera_info
        - /sensing/camera/camera1/camera_info
        - /sensing/camera/camera2/camera_info
        - /sensing/camera/camera3/camera_info
        - /sensing/gnss/clap/ros/imu
        - /sensing/gnss/clap/ros/gps_nav_sat_fix
        - /sensing/gnss/clap/ros/twist_with_covariance_stamped
        - /sensing/gnss/clap/autoware_orientation
        - /sensing/lidar/left/pointcloud_raw
        - /sensing/lidar/right/pointcloud_raw
        - /sensing/lidar/top/pointcloud_raw
        - /vehicle/status/control_mode
        - /vehicle/status/gear_status
        - /vehicle/status/steering_status
        - /vehicle/status/velocity_status
    other_topics:                                           # all other topics
      record_other: false
      other_topics:
        - /sensing/camera/camera0/image_rect
        - /perception/obstacle_segmentation/pointcloud
        - /perception/object_recognition/objects
        - /planning/scenario_planning/trajectory
        - /planning/scenario_planning/lane_driving/behavior_planning/path

