/**:
  ros__parameters:
    lanelet2_map_projector_type: MGRS   # Options: MGRS, UTM
    latitude: 41.023996553613905       # Latitude of map_origin, using in UTM
    longitude: 28.886452364733607      # Longitude of map_origin, using in UTM

    center_line_resolution: 5.0         # [m]
